openapi: 3.0.0
info:
  title: Product Search API
  version: 1.0.0
paths:
  /products:
    get:
      summary: Recherche des produits
      parameters:
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/QueryParam'
      responses:
        '200':
          description: Liste des produits
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                multiple_products:
                  summary: Exemple avec plusieurs produits
                  value:
                    - name: "Laptop"
                      expiration_datetime: "2024-12-31T23:59:59Z"
                      price: 999.99
                    - name: "Smartphone"
                      expiration_datetime: "2025-06-30T23:59:59Z"
                      price: 499.99
                empty_list:
                  summary: Exemple avec liste vide
                  value: []
components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
        expiration_datetime:
          type: string
          format: date-time
        price:
          type: number
          format: float
  parameters:
    LimitParam:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
      example: 10
    QueryParam:
      name: q
      in: query
      required: false
      schema:
        type: string
      example: "laptop"